build:
	javac -sourcepath src -classpath out/production/dpl src/dpl/Main.java -d out/production/dpl
default:build
clean:
	rm -r -f ./out/production/dpl/*
error1:
	cat error1.ltcl
error1x:
	java -classpath out/production/dpl dpl.Main error1.ltcl
error2:
	cat error2.ltcl
error2x:
	java -classpath out/production/dpl dpl.Main error2.ltcl
error3:
	cat error3.ltcl
error3x:
	java -classpath out/production/dpl dpl.Main error3.ltcl
error4:
	cat error4.ltcl
error4x:
	java -classpath out/production/dpl dpl.Main error4.ltcl
error5:
	cat error5.ltcl
error5x:
	java -classpath out/production/dpl dpl.Main error5.ltcl
arrays:
	cat arrays.ltcl
arraysx:
	java -classpath out/production/dpl dpl.Main arrays.ltcl
conditionals:
	cat conditionals.ltcl
conditionalsx:
	java -classpath out/production/dpl dpl.Main conditionals.ltcl
recursion:
	cat recursion.ltcl
recursionx:
	java -classpath out/production/dpl dpl.Main recursion.ltcl
iteration:
	cat iteration.ltcl
iterationx:
	java -classpath out/production/dpl dpl.Main iteration.ltcl
functions:
	cat functions.ltcl
functionsx:
	java -classpath out/production/dpl dpl.Main functions.ltcl
lambda:
	cat lambda.ltcl
lambdax:
	java -classpath out/production/dpl dpl.Main lambda.ltcl
dictionary:
	cat dictionary.ltcl
dictionaryx:
	java -classpath out/production/dpl dpl.Main dictionary.ltcl
problem:
	cat problem.ltcl
problemx:
	java -classpath out/production/dpl dpl.Main problem.ltcl
